### ISSUE TITLE
Some upgrades are not bought thus causing game to lose

### ISSUE THREAD

**Issue by aranthel09** [linus-jansson/btd6farmer#21] opened 2022-07-20 12:14 UTC
Stage starts normally. Both monkeys, subs and hero are placed. However right after they're placed sometimes the bot opens a tower menu but doesn't buy any upgrade and close the tab afterwards. 

After checking Instructions I found that "14" is not being executed.

"14": [
    {
      "TOWER": "SUBMARINE",
      "UPGRADE": "0-0-1",
      "UPGRADE_DIFF": "0-0-1",
      "TARGET": null,
      "TARGET_POS": null,
      "POSITION": [1452, 922],
      "ROUND_START": false
    }
  ],

Am I missing something like turning auto start off? Or maybe my extra 200 money at the beggining is causing it to fail?

Additional info:

Some upgrades after the one mentioned are not bought aswell. Tried turning off monkey knowledge but to no avail.

Screen size: 1920x1080
Monitor: 1920x1080 59.9hz
Windows 10

**Comment by linus-jansson** [comment] 2022-07-20 13:56
> Am I missing something like turning auto start off? Or maybe my extra 200 money at the beggining is causing it to fail?
No that shouldn't be a issue.. 

Will check it out soon, thanks for sharing!

**Comment by linus-jansson** [comment] 2022-07-20 14:20
Hmm after testing, with no MK. Round 14 is being executed on my end.. 

On what round are you losing the game? Also were there any other rounds that you experienced weirdness from the bot?

**Comment by linus-jansson** [comment] 2022-07-21 17:34
Could you try with the latest release to see if the issue is still present?

**Comment by aranthel09** [comment] 2022-07-22 18:45
Tried with latest release but the problem still persists. 14 is still not being executed. Bot opens the sub upgrade menu but doesn't buy 0-0-1

**Comment by linus-jansson** [comment] 2022-07-25 08:51
I've been working on some features in PR #25. Mostly a rework of the instruction system and also some other changes..

Would it be possible for you to try out the [Dev branch](https://github.com/linus-jansson/btd6farmer/tree/dev) to see your problems persist as I have no way to reproducing this?

**Comment by aranthel09** [comment] 2022-07-30 04:11
Debug using the dev branch:
[DEBUG#21.zip](https://github.com/linus-jansson/btd6farmer/files/9224768/DEBUG.21.zip)

Also attached the copy of CMD log since I couldn't find where it was located. 

Debug using main branch:
[DEBUG#21-Main.txt](https://github.com/linus-jansson/btd6farmer/files/9224770/DEBUG.21-Main.txt)

Even though it says every instruction was executed, 14, 21 and 22 weren't. Some others weren't too, thus causing me to lose in round 33.

**Comment by linus-jansson** [comment] 2022-07-30 08:04
did this happen on both branches?

**Comment by aranthel09** [comment] 2022-08-01 18:48
Only on main. Dev didn't work for me; it selects the map but doesn't execute anything once inside the game.

**Comment by linus-jansson** [comment] 2022-09-19 16:07
I am working on the later issue with the bot not executing anything & also looking into the issue of the bot not being accurate on detecting some rounds..

Will however not be fixed on the old version

**Closed by linus-jansson** 2022-09-19 16:07 UTC
Labels: bug
